name: GH Cherrypick bugfixes/features for LTS/Prod

on:
  push:
    branches:
      - cicd-email
      
jobs:

  # Check if the PR is a bugfix/feature
  check_labels:
    runs-on: ubuntu-latest
    name: Send email
    steps:
    - name: Install utils
      run: sudo apt install mailutils -y
        
    - name: Send it
      run: echo "Hello World!" | mail -s "GH Actions Test Email" "jrcain@usgs.gov"